# Requires a pre-downloaded source directory:
# cd ../
# hg clone http://hg.openjdk.java.net/jdk8u/jdk8u
# cd jdk8u
# hg up jdk8u102-b14
# sh get_source.sh

package:
  name: openjdk
  version: 1.8.0.102

build:
  number: 13

source:
  path: ../jdk8u

requirements:
  build:
    - gcc
    - freetype ==2.5.5
    - fontconfig ==2.12.1
    - zlib ==1.2.8
  run:
    - libgcc
    - freetype ==2.5.5
    - fontconfig ==2.12.1
    - zlib ==1.2.8

test:
  commands:
    - java -version

about:
  home: http://openjdk.java.net/
  license: GPLv2
  summary: open-source implementation of the Java Platform, Standard Edition
