# GNU Parallel
# updated to latest from https://github.com/ostrokach/conda-recipes-extra/tree/master/parallel

package:
  name: parallel
  version: 20160622

source:
  url: http://ftpmirror.gnu.org/parallel/parallel-20160622.tar.bz2
  fn: parallel-20160622.tar.bz2
  md5: 2050d01356921fee8b07c531576b5541

requirements:
  build:
  run:
    - perl 5.22.2.1

test:
  commands:
    - parallel --version

about:
  home: http://www.gnu.org/software/parallel/
  license: GPLv3
  summary: GNU parallel is a shell tool for executing jobs in parallel using one or more computers
